apiVersion: v1  #描述文件遵循v1版本的KubernetesAPI
kind: Pod   #我们在描述一个Pod
metadata:
  name: kubia-manual #Pod的名称
spec:
  containers:
  - image: luksa/kubia  #创建容器所用的镜像
    name: kubia   #容器名称
    ports:
    - containerPort: 8080 #应用监听的端口
      protocol: TCP
